/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80030
 Source Host           : localhost:3306
 Source Schema         : ms3

 Target Server Type    : MySQL
 Target Server Version : 80030
 File Encoding         : 65001

 Date: 13/01/2023 17:20:19
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for emulator_texts
-- ----------------------------
DROP TABLE IF EXISTS `emulator_texts`;
CREATE TABLE `emulator_texts`  (
  `key` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `value` varchar(4096) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`key`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of emulator_texts
-- ----------------------------
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_userinfo.forgot_username', 'Please provide an username!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_userinfo', ':userinfo <username>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_shout_all', ':shoutall <message>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_say_all', ':sayall <message>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_shout_all.forgot_message', 'Specify a message!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_control.not_self', 'You cannot control yourself *facepalm*');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_talk', ':talk <username> <message>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_control.not_found', 'User %user% could not be found!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_control.controlling', 'You\'re now controlling %user%!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_alert.forgot_username', 'Please provide a username!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_alert.forgot_message', 'Please provide a message!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_alert.message_send', 'Alert send to %user%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_alert.user_offline', 'Four Oh Four - \\r %user% doesn\'t seem to be online!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.forgot_user', 'Please provide a username!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.forgot_time', 'Please provide a time in seconds!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.invalid_time', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.time_to_short', 'Ban time must be more than 600 seconds (Which equals 10 minutes.)');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.ban_self', 'You cannot ban yourself.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.user_offline', 'Target could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_ban.ban_issued', '%user% banned for %time% seconds with reason %reason%');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_coords.title', '<b>Your current coords</b>');
INSERT INTO `emulator_texts` VALUES ('generic.rotation.head', 'Head Rotation');
INSERT INTO `emulator_texts` VALUES ('generic.rotation.body', 'Body Rotation');
INSERT INTO `emulator_texts` VALUES ('generic.sitting', 'Sitting');
INSERT INTO `emulator_texts` VALUES ('generic.yes', 'Yes');
INSERT INTO `emulator_texts` VALUES ('generic.no', 'No');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_credits.received', 'Whoah! You\'ve received %amount% credits!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_credits.send', '%amount% credits send to %user%!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_credits.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_credits.user_offline', 'User %user% could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_disconnect.forgot_username', 'Please provide a username!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_disconnect.disconnect_self', 'You cannot disconnect yourself!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_disconnect.user_offline', 'User not found.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_disconnect.disconnected', '%user% disconnected!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_freeze_bots.frozen', 'Bots are now frozen.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_freeze_bots.unfrozen', 'Bots can now walk through your room.');
INSERT INTO `emulator_texts` VALUES ('generic.cannot_do_that', 'You cannot do that!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ha.forgot_message', 'Please provide a message!');
INSERT INTO `emulator_texts` VALUES ('generic.pet.name', 'Name');
INSERT INTO `emulator_texts` VALUES ('generic.pet.age', 'Age');
INSERT INTO `emulator_texts` VALUES ('generic.pet.level', 'Level');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_pet_info.stats', '<b>Pet Stats:</b>');
INSERT INTO `emulator_texts` VALUES ('generic.pet.scratches', 'Scratches');
INSERT INTO `emulator_texts` VALUES ('generic.pet.energy', 'Energy');
INSERT INTO `emulator_texts` VALUES ('generic.pet.happyness', 'Happyness');
INSERT INTO `emulator_texts` VALUES ('generic.pet.level.thirst', 'Thirst Level');
INSERT INTO `emulator_texts` VALUES ('generic.pet.level.hunger', 'Hunger Level');
INSERT INTO `emulator_texts` VALUES ('generic.pet.current_action', 'Current action');
INSERT INTO `emulator_texts` VALUES ('generic.can.walk', 'Can walk');
INSERT INTO `emulator_texts` VALUES ('generic.nothing', 'Nothing');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_pet_info.title', '<b>Pet Info</b>');
INSERT INTO `emulator_texts` VALUES ('generic.pet.days.alive', 'days alive.');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_duckets.received', 'Whoah! You\'ve received %amount% duckets!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_duckets.send', '%amount% duckets send to %user%!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_duckets.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_duckets.user_offline', 'User %user% could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_catalog', 'Catalogue has been refreshed!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_items', 'Items have been refreshed!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_permissions', 'Permissions have been refreshed!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_pet_data', 'Petdata have been refreshed!');
INSERT INTO `emulator_texts` VALUES ('error.recycler.box.empty', 'Oops! This box doesn\'t seem to have a prize inside. We\'ll remove it for you.');
INSERT INTO `emulator_texts` VALUES ('error.catalog.buy.not_yet', 'Cannot buy that yet. Hold on <3');
INSERT INTO `emulator_texts` VALUES ('hotel.room.inappropriate.title', 'Inappropriate to hotel management.');
INSERT INTO `emulator_texts` VALUES ('hotel.alert.message.welcome', 'Welcome to Habbo Hotel %user%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_say.forgot_username', 'Please provide a username!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_say.user_not_found', 'User not found.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_say.hotel_view', '%user% is not in a room!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_say', '%user% said %message%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_shout.forgot_username', 'Please provide a username!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_shout.hotel_view', '%user% is not in a room!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_shout.user_not_found', 'User not found.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_shout', '%user% shouted %message%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_setspeed.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_setspeed.bounds', 'Please use a number between 0 and 100.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_setspeed', 'Succes! Old speed: %oldspeed%. New Speed: %newspeed%.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_teleport.enabled', 'Teleporting enabled!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_teleport.disabled', 'Teleporting disabled!');
INSERT INTO `emulator_texts` VALUES ('error.pets.max.inventory', 'You\'ve reached the maximum amount of pets in your inventory! The Limit is %amount%!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_control', ':control <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_say_all.forgot_message', 'Specify a message!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_control.stopped', '%user% is now a free man!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_points.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_points.user_offline', 'User %user% could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_points.send', '%amount% %type% send to %user%!');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_points.received', 'Whoah! You\'ve received %amount% %type%!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_update_texts.failed', 'Failed to update texts!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_texts', 'Updated texts!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_hand_item', ':handitem <itemid>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_freeze_bots', ':freezebots');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_shout', ':makeshout <username> <text>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_points', ':points <username> <amount> [type]');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_enable', ':enable <effect id>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_texts', ':update_texts');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_ban', ':ban <username> <time in seconds>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_say', ':say <username> <text>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_permissions', ':update_permissions');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_pet_info', ':petinfo <petname>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_setspeed', ':setspeed <speed>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_pet_data', ':update_petdata');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_about', ':about');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_alert', ':alert <username> <message>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_commands', ':commands');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_coords', ':coords');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_credits', ':credits <username> <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_disconnect', ':disconnect <username>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_duckets', ':duckets <username> <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_ha', ':ha <message>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_kickall', ':kickall <message>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_setpublic', ':setpublic');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_shutdown', ':shutdown');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_teleport', ':teleport');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_unload', ':unload');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_catalogue', ':update_catalog');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_items', ':update_items');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_userinfo.not_found', 'User %user% not found!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_masscredits.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_massduckets.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_masspoints.invalid_amount', 'Please use a valid number.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_masscredits', ':masscredits <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_massduckets', ':massduckets <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_masspoints', ':masspoints <amount> [type] ');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_sitdown', ':sitdown');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_pull.pull', '* Pulls %user% towards %gender_name% *');
INSERT INTO `emulator_texts` VALUES ('gender.him', 'him');
INSERT INTO `emulator_texts` VALUES ('gender.her', 'her');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_pull.not_found', 'User %user% could not be found!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_push.push', '* Pushes %user% away from %gender_name% *');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_pull.cant_reach', 'User %user% is too far away!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_push.cant_reach', 'User %user% is too far away!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_pull', ':pull <username>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_push', ':push <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_pull.pull_self', 'You cannot pull yourself!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_push.push_self', 'You cannot push yourself!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_push.not_found', 'User %user% could not be found!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_superpull', ':spull <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mute.not_found', 'Use %user% could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_danceall.invalid_dance', 'Please use a valid number!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_danceall.outside_bounds', 'Please use a number between 0 and 4');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_freeze.not_found', 'User %user% could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_freeze.user_frozen', 'User %user% frozen!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_freeze.user_unfrozen', 'User %user% unfrozen!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_freeze.frozen', 'You\'ve been frozen!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_freeze.unfrozen', 'You\'ve been unfrozen!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_danceall', ':danceall <dance id>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_freeze', ':freeze <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mimic.not_found', 'User %user% could not be found!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mimic.not_self', 'You cannot copy yourself!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_mimic', ':mimic <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mimic.blocked', 'You cannot copy %user% %gender_name% look!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mimic.copied', 'You copied %user% %gender_name% look!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mute.not_specified', 'Please specify an user to mute.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mute.muted', 'User %user% is now muted.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mute.unmuted', 'User %user% is no longer muted.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mute.self', 'You cannot mute yourself. ');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_mute', ':mute <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_badge.forgot_username', 'Please specify an user to give a badge to.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_badge.forgot_badge', 'Please specify an badge to give to %user%.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_badge.already_owns', 'User %user% already owns %badge%.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_badge.given', 'Given %badge% to %user%!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_badge', ':badge <username> <badge>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_enable.not_allowed', 'You do not have permission to set this effect!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_about', 'info;about;help');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_alert', 'alert;warning');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_badge', 'badge;givebadge');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_ban', 'ban');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_commands', 'commands;cmds');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_control', 'control');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_coords', 'coords;cordinates;coordinates;position');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_credits', 'credits;coins');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_disconnect', 'dc;disconnect;kill');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_enable', 'enable;effect');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_freeze_bots', 'freeze_bot;freezebot;freezebots;freeze_bots');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_freeze', 'freeze');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_hand_item', 'handitem;item;hand');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_ha', 'hotelalert;ha');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_masscredits', 'mass_credits;masscredits');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_massduckets', 'mass_duckets;massduckets;mass_pixels;masspixels');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_masspoints', 'mass_points;masspoints');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_mimic', 'mimic;copy');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_mute', 'mute;shutup');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_pet_info', 'pet;pet_info;petinfo');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_duckets', 'pixels;duckets');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_points', 'diamonds;points');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_pull', 'pull');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_push', 'push');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_danceall', 'danceall;room_dance;roomdance');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_kickall', 'room_kick;kickall;roomkick;kick_all');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_say_all', 'sayall;say_all');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_say', 'say;makesay');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_setspeed', 'speed;setspeed');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_shout_all', 'shoutall;shout_all;roomshout;room_shout');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_shout', 'makeshout');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_shutdown', 'stop;shutdown');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_sitdown', 'sitall;sitdown');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_superpull', 'spull;superpull');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_teleport', 'tele;teleport');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_unload', 'crash;unload');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_catalogue', 'reload_catalogue;reload_cata;update_catalogue;update_cata;update_catalog;update_shop');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_items', 'update_items;reload_items');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_permissions', 'update_permissions;update_perms');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_pet_data', 'update_pet_data;update_petdata');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_texts', 'update_texts;reload_texts');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_userinfo', 'userinfo;user_info');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_sit', 'sit');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_sit', ':sit');
INSERT INTO `emulator_texts` VALUES ('total', 'Total');
INSERT INTO `emulator_texts` VALUES ('generic.bot.name', 'Bot');
INSERT INTO `emulator_texts` VALUES ('generic.bot.id', 'ID');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_bots', ':bots');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_bots', 'bots');
INSERT INTO `emulator_texts` VALUES ('generic.shutdown', 'The server is shutting down. All changes made from now on may not get saved!');
INSERT INTO `emulator_texts` VALUES ('generic.reason.specified', 'Reason specified');
INSERT INTO `emulator_texts` VALUES ('generic.warning', 'WARNING!');
INSERT INTO `emulator_texts` VALUES ('wired.variable.username', '%username%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.credits', '%credits%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.points', '%points%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.pixels', '%pixels%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ban.target_rank_higher', 'The Habbo you want to ban has a higher rank than you.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_unban.not_specified', 'No username specified!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_unban.success', '%user% has been unbanned.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_unban.not_found', 'No bans found for %user%.');
INSERT INTO `emulator_texts` VALUES ('unbanned', 'unbanned');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_unban', ':unban <username>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_unban', 'unban');
INSERT INTO `emulator_texts` VALUES ('stalk.failed.same.room', '%user% is in this room too!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_trash', 'trash;tornado;sharknado');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_empty.cleared', 'Inventory cleared!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_empty.verify', 'This will remove all items from your inventory. Type :empty %generic.yes% to continue!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_wordfilter', 'Wordfilter reloaded!');
INSERT INTO `emulator_texts` VALUES ('warning.auto.report', '%user% triggered wordfilter using: %word%');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_empty', 'empty');
INSERT INTO `emulator_texts` VALUES ('commands.keys.update_wordfilter', 'update_wordfilter;update_filter;update_word_filter');
INSERT INTO `emulator_texts` VALUES ('commands.description.acc_debug', ':test [header] i:1 s:a b:1');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_trash', ':trash');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_wordfilter', ':update_word_filter');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_config', 'update_config;update_configuration');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.room.delete', '%username% tried to delete %roomname% owned by %roomowner%');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_config', 'Configuration reloaded!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_guildparts', 'update_guildparts;update_guild_parts');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_guildparts', ':update_guild_parts');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_config', ':update_config');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_empty', ':empty <username>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_plugins', 'update_plugins;updateplugins');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_plugins', ':update_plugins');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_plugins', 'Reloaded %count% plugins!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_happyhour', 'happyhour;happy_hour');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_danceall.no_dance', 'Please specify a dance from 0 to 4!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roomeffect', 'roomeffect;room_effect');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roomeffect.no_effect', 'No effect specified!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roomeffect.numbers_only', 'Use numbers only!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roomeffect.positive', 'Positive numbers only!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_staffonline.numbers_only', 'Numbers only please!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_staffonline.positive_only', 'Positive numbers only please!');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_staffonline.staffs', '<b>Staffs online:</b>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_staffonline', ':staffonline [minrank]');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roomeffect', ':roomeffect [effect id]');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_staffonline', 'staffonline;staffs');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_happyhour', ':happyhour');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_summon', 'summon');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_summon', ':summon <username>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_summon.forgot_username', 'Specify the username of the Habbo you want to summon!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_summon.not_found', '%% is not online!');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_summon.same_room', '%user% is in this room already!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_summon.summoned', '%user% summoned!');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_summon.been_summoned', 'You\'ve been summoned by %user%!');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_summon.summoning', 'Summoning %user%...');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roomitem.no_item', 'No item id specified!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roomitem.positive', 'Positive numbers only!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_roomitem.given', 'Handitem %item% given!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_roomitem.removed', 'Handitems removed!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roomitem', 'roomitem;room_item');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roomitem', ':roomitem [itemid]');
INSERT INTO `emulator_texts` VALUES ('pirate_parrot.message.0', 'Yarr');
INSERT INTO `emulator_texts` VALUES ('pirate_parrot.message.1', 'Do what you want cos a pirrrrate is free');
INSERT INTO `emulator_texts` VALUES ('pirate_parrot.message.2', 'Gimme some ale matey');
INSERT INTO `emulator_texts` VALUES ('pirate_parrot.message.3', 'potato');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_chatcolor', 'chat;chatcolor');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_chatcolor.numbers', 'Positive numbers only please!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_chatcolor.no_number', 'Please provide an color id.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_chatcolor.banned', 'Sorry, that chatcolor is not allowed.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_chatcolor.set', 'Your new chatcolor is: %chat%');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_chatcolor.reset', 'Chat reset to normal');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_chatcolor', ':chat [colorid = 0]');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_masspoints.invalid_type', 'Invalid points type. Choose from: %types%');
INSERT INTO `emulator_texts` VALUES ('seasonal.name.0', 'Pixels');
INSERT INTO `emulator_texts` VALUES ('seasonal.name.105', 'Diamonds');
INSERT INTO `emulator_texts` VALUES ('seasonal.name.101', 'Snowflakes');
INSERT INTO `emulator_texts` VALUES ('seasonal.name.104', 'Clouds');
INSERT INTO `emulator_texts` VALUES ('seasonal.name.4', 'Shells');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_points.invalid_type', 'Invalid points type. Choose from: %types%');
INSERT INTO `emulator_texts` VALUES ('pirate_parrot.message.4', 'You dirty \'lil cunt');
INSERT INTO `emulator_texts` VALUES ('bots.visitor.no_visits', 'There were no visitors when you were away.');
INSERT INTO `emulator_texts` VALUES ('bots.visitor.visits', 'There were %count% visits since the last time you were away. If you want me to tell them say %positive%');
INSERT INTO `emulator_texts` VALUES ('bots.visitor.list', 'Last %count% visits were: %list%');
INSERT INTO `emulator_texts` VALUES ('generic.time.at', 'at');
INSERT INTO `emulator_texts` VALUES ('bots.butler.given', 'Here is your %key% %username%');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_multi', 'multi');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_multi', ':multi');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_stalk.not_found', '%user% seems to be offline.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_stalk.not_room', '%user% seems to be outside of an room.');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_stalk.same_room', '%user% seems to be in this room already!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_stalk', 'stalk;follow;rape');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_stalk', ':stalk <username>');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_summonrank.error', 'Potatohead!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_summonrank', 'summonrank;summonall');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_summonrank', ':summonrank <rankid>');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_summon.self', 'I tried something silly.');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_stalk.self', 'I tried something silly');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_bundle', 'bundle;roombundle');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_bundle', ':bundle');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_bundle.missing_params', 'Proper usage is :bundle <parent_id> <credits> <points> <points_type>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_bundle.duplicate', 'Whoops! Looks like this room is already on sale.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mute.time', 'Mute time must be atleast 1 second.');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.catalog.count', '%username% tried to buy multiple items of %itemname% from page %pagename% altough these are no set to have offers enabled!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.look.gender', '%username% tried to script an invalid gender \'%gender%\'');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.catalog.page', '%username% tried to access a page it doesn\'t have permission to: %pagename%');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.guild.buy.owner', '%username% tried to buy a guild for room %roomname% owned by %owner%');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.roomsettings.category.nonexisting', '%username% tried to set its room to a non existing category!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.roomsettings.category.permission', '%username% tried to set its room to a category it doesn\'t have acces to: %category%');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_event', 'event;roomevent');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_event', ':event <message>');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.catalog.badge_display', '%username% tried to buy a badge display with badge %badge% which isn\'t owned!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.alert', '%username% tried to send an alert (\'%message%\') without having permission to modtools!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.ban', '%username% tried to ban someone trough modtools without having rights to ban!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.roomsettings', '%username% tried to edit an room via modtool without having permissions!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.ticket.close', '%username% tried to close a ticket without having permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.kick', '%username% tried to kick someone via modtools without having permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.ticket.pick', '%username% tried to pick a ticket in modtools without having permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.ticket.release', '%username% tried to release tickets in modtool without having permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.chatlog', '%username% requested chatlog in modtool without having permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.modtools.roominfo', '%username% requested roominfo in modtools without permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.userinfo', '%username% requested userinfo in modtools without permission!');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.roomalert', '%username% tried to send a roomalert in modtools without permission!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_blockalert', 'Alerts are now turned %state%');
INSERT INTO `emulator_texts` VALUES ('generic.on', 'on');
INSERT INTO `emulator_texts` VALUES ('generic.off', 'off');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_blockalert', 'blockalerts;blockalert;ignorealerts;ignore_alerts');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_blockalert', ':blockalert');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_faceless', 'faceless;face');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_faceless', ':faceless');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_moonwalk', 'moonwalk;mj;moon_walk');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_moonwalk', ':moonwalk');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_fastwalk', 'fastwalk;supersonic');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_fastwalk', ':fastwalk');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_redeem', 'redeem;exchange');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_redeem', ':redeem');
INSERT INTO `emulator_texts` VALUES ('generic.redeemed', 'Redeemed: ');
INSERT INTO `emulator_texts` VALUES ('generic.credits', 'credits');
INSERT INTO `emulator_texts` VALUES ('generic.pixels', 'pixels');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_gift.not_a_number', 'Only positive numbers');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_gift', 'gift');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_gift.not_found', '%itemid% not found!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_gift.user_not_found', '%username% not found online.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_gift', 'Send %itemname% to %username%!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_gift', ':gift <username> <itemid>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_massgift', 'massgift');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_massgift', ':massgift <itemid>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_badge.already_owned', '%user% already owns %badge%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_massbadge.no_badge', 'No badge specified!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_massbadge', 'massbadge;hotelbadge');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_badge.received', 'Yahoooo! You\'ve received a badge!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_pickall', 'pickall;pickupall');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_ejectall', 'ejectall;ejectfurni');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_bots', 'update_bots;updatebots');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_ejectall', ':ejectall');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_pickall', ':pickall');
INSERT INTO `emulator_texts` VALUES ('', '');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_staffalert', 'sa;staffalert');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_staffalert.title', '<b>Staff Alert:</b>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_staffalert.forgot_message', 'Please specify a message to send to staff.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_plugins', 'plugins');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_hotel_view', 'update_view;update_hotel_view;update_hotelview');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_hotel_view', ':update_hotel_view');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_hotel_view', 'Hotelview reloaded!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_bundle', 'Roombundle succesfully created with page id %id%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_kick.unkickable', '%username% is unkickable!');
INSERT INTO `emulator_texts` VALUES ('camera.disabled', 'Sorry! Camera is disabled :(');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_navigator', 'update_navigator;update_nav');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_navigator', 'Navigator succesfully reloaded!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_plugins', ':plugins');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_massbadge', ':massbadge <badge>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_bots', ':update_bots');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_navigator', ':update_navigator');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_ip_ban', 'ipban;banip;ip_ban;ban_ip');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_ip_ban', ':ipban <username> [reason]');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_machine_ban', 'machineban;banmachine;banmac;macban');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_machine_ban', ':machineban <username> [reason]');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_super_ban', 'superban;megaban');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_super_ban', ':superban <username> [reason]');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_machine_ban', '%count% accounts have been MAC banned!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_ip_ban', '%count% accounts have been IP banned!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_super_ban', '%count% accounts have been Super banned!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_ip_ban.ban_self', 'You cannot IP Ban yourself!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_machine_ban.ban_self', 'You cannot issue yourself a MAC Ban!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_super_ban.ban_self', 'You cannot superban yourself!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_alert.cmd_connect_camera', 'Camera reconnected!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_connect_camera', 'connectcamera;connect_camera;cameraconnect');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_disconnect.higher_rank', 'The Habbo you wanted to disconnect is more important than you are.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_diagonal', 'diagonal;disablediagonal;diagonally');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_diagonal', ':diagonal');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_diagonal.disabled', 'You can no longer walk diagonally!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_word_quiz', 'wordquiz;quiz');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_word_quiz', ':wordquiz <question>');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.marketplace.forbidden', '%username% tried to sell an %itemname% for %credits% which is not allowed to be sold on the marketplace!');
INSERT INTO `emulator_texts` VALUES ('inventory.full', 'You\'ve reached the inventory limit. Move furniture out of your inventory before buying more!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_setmax.invalid_number', 'Invalid number. Specify a number between 0 and 9999');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_setmax.forgot_number', 'No number specified. Dork.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_setmax', 'setmax;set_max');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_setmax', ':setmax <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_staffalert', ':sA <message>');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_take_badge', ':takebadge <username> <badge>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_take_badge', 'takebadge;take_badge;remove_badge;removebadge');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_take_badge.forgot_badge', 'No badge specified!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_take_badge.forgot_username', 'No username specified!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_take_badge.no_badge', '%username% does not have %badge%!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_take_badge', 'Badge has been taken!');
INSERT INTO `emulator_texts` VALUES ('camera.permission', 'You don\'t have permission to use the camera!');
INSERT INTO `emulator_texts` VALUES ('floorplan.permission', 'You don\'t have permission to use the floorplan editor!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_polls', 'update_polls;reload_polls');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_polls', ':update_polls');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_set_poll', 'setpoll;set_poll');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_set_poll', ':setpoll <id>');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_set_poll', 'Room poll has been updated!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_set_poll.invalid_number', 'Please specify a valid number. Use 0 to remove the poll.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_set_poll.missing_arg', 'Missing poll id. Use 0 to remove the poll from this room.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roomcredits', 'roomcredits;room_credits;roomcoins;room_coins');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roomcredits', ':roomcredits <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roompixels', 'roompixels;room_pixels;roomduckets;room_duckets');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roompixels', ':roompixels <amount>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roomgift', 'roomgift;room_gift');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roomgift', ':roomgift <item_id> [message]');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_polls', 'Room polls have been reloaded!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_set_poll.not_found', 'Poll %id% not found!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_unmute.not_specified', 'No user specified to unmute!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_unmute.not_found', '%user% is not online!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_unmute', '%user% has been unmuted!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_unmute', 'unmute');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_unmute', ':unmute <username>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_give_rank', 'giverank;setrank;give_rank;set_rank');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_give_rank', ':giverank <username> <rank>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_give_rank.not_found', 'Rank %id% was not found!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_give_rank.updated', '%username% has been given the rank %id%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_give_rank.higher', 'You cannot rank %username% to a higher rank than you are!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_give_rank.user_offline', '%username% is not online!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_give_rank.missing_rank', 'Missing rank. Usage: ');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_give_rank.missing_username', 'Missing username. Usage: ');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_give_rank.new_rank', 'Your rank has been updated. Your rank is now %id%');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roommute', 'roommute;room_mute');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roommute', ':roommute');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_roommute.unmuted', 'The room has been unmuted!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_roommute.muted', 'The room has been muted!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_lay', 'lay');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_lay', ':lay');
INSERT INTO `emulator_texts` VALUES ('camera.wait', 'Please wait %seconds% seconds before making another picture.');
INSERT INTO `emulator_texts` VALUES ('loggedin.elsewhere', 'You have been disconnected as you logged in from somewhere else.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_mute_pets', 'mutepets;ignorepets;mute_pets;ignore_pets');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mute_pets.ignored', 'You\'re now ignoring pets.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mute_pets.unignored', 'You\'re no longer ignoring pets.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_mute_bots', 'mutebots;ignorebots;mute_bots;ignore_bots');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mute_bots.ignored', 'You are now ignoring bots.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_mute_bots.unignored', 'You are no longer ignoring bots.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roomalert', ':roomalert <message>');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roomalert.empty', 'Please specify an message!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roomalert', 'roomalert;room_alert;ra');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roompoints', 'roompoints;room_points');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_transform.title', 'The following pets are available:');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_transform.line', '%name%');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_transform', ':transform <name> <race> <color>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_transform', 'transform;becomepet');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_connect_camera', ':connectcamera');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roompoints', ':roompoints <amount>');
INSERT INTO `emulator_texts` VALUES ('generic.gift.received.anonymous', 'You\'ve received a gift!');
INSERT INTO `emulator_texts` VALUES ('generic.gift.received', '%username% gave you a gift!');
INSERT INTO `emulator_texts` VALUES ('generic.user.not_found', '%user% not found.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_reload_room', 'reload_room;reload;reloadroom');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_reload_room', ':reload_room');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.packet.closedice', '%username% tried to change furniture state on non dice using the close dice packet on item %id% %itemname%');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_guildparts', 'Succes! Guild badgeparts and guild badge imager has been reloaded!');
INSERT INTO `emulator_texts` VALUES ('ban.info.user_id', 'User ID: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.type', 'Ban Type: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.reason', 'Reason: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.staff_id', 'Staff ID: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.date_issued', 'Date: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.date_expire', 'Expire Date: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.ip', 'IP: ');
INSERT INTO `emulator_texts` VALUES ('ban.info.machine', 'Machine: ');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.user_id', 'ID');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.user_name', 'Username');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.motto', 'Motto');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.rank', 'Rank');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.online', 'Online');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.email', 'Email');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.ip_register', 'Register IP');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.ip_current', 'Current IP');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.banned', 'Banned');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.currencies', 'Currencies');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.achievement_score', 'Score');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.credits', 'Credits');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.current_activity', 'Current Activity');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.room', 'Room');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.respect_left', 'Respect Left');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.pet_respect_left', 'Pet Respect Left');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.allow_trade', 'Allow Trade');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.allow_follow', 'Allow Follow');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.allow_friend_request', 'Allow Friend Request');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.total_bans', 'Total bans');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.ban_info', 'Recent Ban Info');
INSERT INTO `emulator_texts` VALUES ('command.cmd_userinfo.userinfo', 'Userinfo');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_pet_info.pet_not_found', '\"Please provide a petname!\"');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_hal', ':hal <url> <message>');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_hal', 'hal;halink');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_empty_bots.cleared', 'Bots inventory cleared!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_empty_bots.verify', 'This will remove all bots from your inventory. Type :emptybots %generic.yes% to continue!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_empty_bots', 'emptybots;empty_bots;deletebots');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_empty_bots', ':emptybots');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_empty_pets.cleared', 'Pets inventory cleared!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_empty_pets.verify', 'This will remove all pets from your inventory. Type :emptypets %generic.yes% to continue!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_empty_pets', 'emptypets;empty_pets;deletepets');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_empty_pets', ':emptypets');
INSERT INTO `emulator_texts` VALUES ('nux.step.1', 'This is the reception button, it will take you to the hotelview.');
INSERT INTO `emulator_texts` VALUES ('nux.step.2', 'This is the navigator button, from here you can visit other rooms.');
INSERT INTO `emulator_texts` VALUES ('nux.step.3', 'To talk, just enter your message here.');
INSERT INTO `emulator_texts` VALUES ('nux.step.4', 'The chat history window lets you read back your previous conversations.');
INSERT INTO `emulator_texts` VALUES ('nux.step.5', 'If you want to change your looks, you can use the wardrobe.');
INSERT INTO `emulator_texts` VALUES ('nux.step.6', 'In the catalog you can purchase furniture to decorate your own room.');
INSERT INTO `emulator_texts` VALUES ('nux.step.7', 'Furniture can be bought with a combination of credits...');
INSERT INTO `emulator_texts` VALUES ('nux.step.8', '...duckets,');
INSERT INTO `emulator_texts` VALUES ('nux.step.9', 'or diamonds.');
INSERT INTO `emulator_texts` VALUES ('nux.step.10', 'All your friends are located down here.');
INSERT INTO `emulator_texts` VALUES ('nux.step.11', 'Lets have some fun and start exploring the hotel!');
INSERT INTO `emulator_texts` VALUES ('alert.superwired.invalid', 'Invalid superwired configuration. Make sure to NOT use <b>;</b> in the product field!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_allow_trading', 'Enables / Disables the tradelock for a user.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_allow_trading', 'tradelock;blocktrading;disabletrade');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_allow_trading.forgot_username', 'Please specify the user to enable / disable trading for.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_allow_trading.forgot_trade', 'Please specify if you want to enable trading for %username%.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_allow_trading.enabled', 'Trading has been enabled for %username%!');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_allow_trading.disabled', 'Trading has been disabled for %username%!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_allow_trading.user_not_found', 'Target Habbo does not exist.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_allow_trading.incorrect_setting', 'Please use %enabled% to enable trading. Use %disabled% to disable trading.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_give_rank.higher.other', '%username% has an higher rank than you and thus cannot change it!');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_unmute.not_muted', '%user% is not muted.');
INSERT INTO `emulator_texts` VALUES ('supporttools.not_ticket_owner', 'You are not the moderator currently handling the ticket.');
INSERT INTO `emulator_texts` VALUES ('commands.success.cmd_setmax', 'Success! Maximum users in this room changed to %value%.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_changename', ':changename');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_changename', 'changename;flagme;change_name;namechange');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_credits.user_not_found', 'Could net send %amount% credits to %user%. %user% does not exist.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_pull.invalid', 'You cannot pull %username% to there.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_push.invalid', 'You cannot push %username% to there.');
INSERT INTO `emulator_texts` VALUES ('hotel.wired.superwired.info', 'Superwired Usage Information. Possible reward types:<br/>badge: BADGE CODE<br/>Credits: credits#amount<br/>Pixels: pixels#amount<br/>Points: points#amount<br/>Respect: respect#amount<br/>Furniture: furni#FurnitureID<br/>Catalog Item: cata#CatalogItemID');
INSERT INTO `emulator_texts` VALUES ('hotel.wired.kickexception.unkickable', 'Wired Kick Exception: Unkickable');
INSERT INTO `emulator_texts` VALUES ('hotel.wired.kickexception.owner', 'Wired Kick Exception: Room Owner');
INSERT INTO `emulator_texts` VALUES ('error.catalog.buy.limited.daily.item', 'You cannot purchase any limited %itemname% for today as you have reached the limt of %limit%. Come back tomorrow.');
INSERT INTO `emulator_texts` VALUES ('error.catalog.buy.limited.daily.total', 'You cannot purchase any limited furniture as you have reached the limited of %limit% for today. Come back tomorrow.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_calendar', 'calendar');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_calendar', ':calendar');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.chat.length', '%username% tried to send a room chat message with length %length% while the maximum length is 100 characters.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_invisible', 'invisible;hideme');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_invisible', ':invisible');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_invisible.updated', 'You are now invisible. Reload the room to reset.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_hidewired', 'hidewired;hidemywired;wiredbegone');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_hidewired.hidden', 'Wired is now hidden.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_hidewired.shown', 'Wired is now shown.');
INSERT INTO `emulator_texts` VALUES ('commands.errors.cmd_hidewired.permission', 'You don\'t have permission to hide wireds in this room!');
INSERT INTO `emulator_texts` VALUES ('support.ticket.picked.failed', 'Picking issue failedd: <br>Ticket already picked or does not exist!');
INSERT INTO `emulator_texts` VALUES ('camera.error.creation', 'Failed to create your picture. *sadpanda*');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.sticky.size', '%username% tried to create a sticky with %amount% characters where %limit% characters are allowed!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_promote_offer', 'promoteoffer;promotetargetoffer;promote_offer');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_promote_offer', ':promoteoffer <offer_id> [info]');
INSERT INTO `emulator_texts` VALUES ('commands.cmd_promote_offer.info', 'info');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_promote_offer.not_found', 'The offer could not be found. Use :promoteoffer info to see a list of active offers.');
INSERT INTO `emulator_texts` VALUES ('commands.cmd_promote_offer.list', 'All available offers (%amount%):<br>%list%');
INSERT INTO `emulator_texts` VALUES ('commands.cmd_promote_offer.list.entry', '%id%: %title% %description%');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_promote_offer', 'The promoted offer has been changed to %id%: %title%');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_filterword', 'filter;banword;filterword');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_filterword.missing_word', 'Please specify the word to filter, with an optional replacement.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_filterword.error', 'Failed to add the word to the wordfilter. Possible duplicate?');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_filterword.added', 'Wordfilter word %word% has been added with replacement %replacement%!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_filterword', ':filter <word> [replacement]');
INSERT INTO `emulator_texts` VALUES ('debug.show.headers', '');
INSERT INTO `emulator_texts` VALUES ('generic.tile.not.exists', 'Tile does not exist!');
INSERT INTO `emulator_texts` VALUES ('commands.errors.cmd_give_rank.not_found', 'Rank %id% could not be given to %username% as it does not exist!');
INSERT INTO `emulator_texts` VALUES ('hotel.wired.giveachievement.invalid.points', 'This is not a number!');
INSERT INTO `emulator_texts` VALUES ('hotel.wired.giveachievement.invalid.achievement', '%achievement% does not exist!');
INSERT INTO `emulator_texts` VALUES ('hotel.error.roomads.nopermission', 'You have no permission to modify room ads!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_achievements', 'uach;update_achievements');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_achievements', ':update_achievements');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_achievements.updated', 'Achievements have been reloaded!');
INSERT INTO `emulator_texts` VALUES ('invisible.prevent.chat.error', 'While being invisible you cannot talk.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_invisible.updated.back', 'You are now visible again.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_mimic.forbidden_clothing', 'The other user has clothing that you do not own yet.');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_youtube_playlists', 'update_youtube;update_youtube_playlists');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_update_youtube_playlists', 'YouTube playlists have been refreshed!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_add_youtube_playlist', 'add_youtube;add_playlist;add_youtube_playlist');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_add_youtube_playlist.usage', 'Usage: base_item_id youtube_playlist_id');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_add_youtube_playlist.no_base_item', 'A base item with that ID could not be found.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_add_youtube_playlist.failed_playlist', 'Error: unable to fetch the given YouTube playlist.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_add_youtube_playlist', 'The playlist has been added successfully!');
INSERT INTO `emulator_texts` VALUES ('generic.furniture.bought', 'You just purchased %amount%%is_limited%%itemname%%limited_display%!');
INSERT INTO `emulator_texts` VALUES ('generic.furniture.sold', 'Your %item% has been sold. Click here to claim your credits!');
INSERT INTO `emulator_texts` VALUES ('commands.generic.cmd_commands.text', 'Your Commands');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_stand', 'stand');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_setstate', ':ss');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setstate.keys', 'ss;setstate');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setstate.changed', 'Changed state to %extra_data%');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setstate.disabled', 'state removed.');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setstate.not_specified', 'No state set. state must be between 0 - 40.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_buildheight', ':buildheight [height]');
INSERT INTO `emulator_texts` VALUES ('be.cmd_buildheight.keys', 'buildheight;bh');
INSERT INTO `emulator_texts` VALUES ('be.cmd_buildheight.invalid_height', 'Invalid height! Build height must be between 0 - 40!');
INSERT INTO `emulator_texts` VALUES ('be.cmd_buildheight.changed', 'Changed build height to %height%');
INSERT INTO `emulator_texts` VALUES ('be.cmd_buildheight.disabled', 'Build height removed.');
INSERT INTO `emulator_texts` VALUES ('be.cmd_buildheight.not_specified', 'No buildheight set. Height must be between 0 - 40.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_setrotation', ':rot;rotation');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setrotation.keys', 'rot;setrotation');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setrotation.changed', 'Changed Furni Rotation to %rot%');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setrotation.disabled', 'Furni Rotation removed.');
INSERT INTO `emulator_texts` VALUES ('be.cmd_setrotation.not_specified', 'No rotation set. state must be between 0 - 6.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_buyroom', ':buyroom');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_sellroom', ':sellroom <diamonds>');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.keys', 'sellroom');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.removed', 'This room was remove from sale.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.invalid_credits', '%diamonds% diamonds is an invalid amount!');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.has_guild', 'Cannot sell this room, room has a guild.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.confirmed', 'This room is now up for sale for %currency% diamonds!');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.usage', 'Usage: :sellroom <diamonds>');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.forsale', 'This room is being sold by %ownername% for %currency% diamonds! If you wish to buy it write :buyroom confirm.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.notforsale', 'This room is not being sold.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.confirmkey', 'confirm');
INSERT INTO `emulator_texts` VALUES ('rosie.buyroom.has_guild', 'This room has a guild and therefor cannot be bought.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.bubble.thisroom', 'This room is for sale for %currency% diamonds!');
INSERT INTO `emulator_texts` VALUES ('rosie.buyroom.bubble.message', 'This room has been bought from %oldowner% by %newowner%!');
INSERT INTO `emulator_texts` VALUES ('rosie.buyroom.bubble.message.bought', '%roomname% has been bought by %newowner%');
INSERT INTO `emulator_texts` VALUES ('rosie.buyroom.invalid_amount', 'You don\'t have enough diamonds to buy this room!');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.owneroffline', 'Owner of this room, %username%, is offline.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.selfbuy', 'Silly %username%. You cannot buy your own room.');
INSERT INTO `emulator_texts` VALUES ('rosie.sellroom.buyroom.usage', 'To buy a room use :%key% %confirmkey%');
INSERT INTO `emulator_texts` VALUES ('rosie.buyroom.keys', 'buyroom');
INSERT INTO `emulator_texts` VALUES ('rosie.roomforsale.alert', 'This room is for sale. Type :buyroom for more information.');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.keys', 'pay;transfer');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.incorrect.usage', 'Missing arguments for pay command!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_pay', ':pay <username> <amount> <currency>');
INSERT INTO `emulator_texts` VALUES ('generic.habbo.notfound', 'Habbo not found');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.self', 'You cannot pay yourself, silly!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.invalid_amount', 'Invalid amount! Please use a positive value.');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.not_enough', 'Cannot pay %username%. You don\'t have %amount% %type%!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.invalid_type', 'The currency %type% does not exist!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.received', '%username% has paid you %amount% %type%!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_pay.transferred', 'You paid %username% %amount% %type%!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_kill', ':kill <username>');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_kill.keys', 'kill;murder');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_kill.killmessages.killer', '* Murders %victim% *;* %victim% was slain by %killer% *;* Takes %victim%s head off *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_kill.killmessages.victim', '* Bleeds to dead while twitching *; * Oh noes. %killer% took my head off *');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_hoverboard', ':hoverboard');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_hoverboard.keys', 'hoverboard');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_hoverboard.texts', '* Grabs Blue hoverboard and flies away *;* Jumps onto a pink hoverboard *;* Nice day to ride my yellow hoverboard *;* Pulls out a green hoverboard to explore the hotel on *');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_kiss', ':kiss <username>');
INSERT INTO `emulator_texts` VALUES ('essentials.kissedmessages.kissedperson', '* %kissedperson% gets kissed by %kisser% *');
INSERT INTO `emulator_texts` VALUES ('essentials.kissedmessages.kisser', '* Kisses %kissedperson% passionately *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_kiss.keys', 'kiss;frenchkiss');
INSERT INTO `emulator_texts` VALUES ('essentials.kissmessages.tofar', '%kissedperson% is too far to kiss!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_hug', ':hug <username>');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_hug.keys', 'hug;cuddle');
INSERT INTO `emulator_texts` VALUES ('essentials.hugmessages.huggedperson', '* Gets a warm hug from %hugger% *');
INSERT INTO `emulator_texts` VALUES ('essentials.hugmessages.hugger', '* Hugs %huggedperson% tightly *');
INSERT INTO `emulator_texts` VALUES ('essentials.hugmessages.tofar', '%huggedperson% is too far to hug. Get a bit closer and try again!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_welcome', ':welcome <username>');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_welcome.keys', 'welcome;willkommen;welkom;bienvenue;bienvenida;bem-vindo');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_welcome.text', 'Welcome %username% to %hotelname%;My name is %greeter_username% and I am %greeter_rank% at %hotelname%;At the moment there are %onlinecount% %hotelplayername%s online!;If you have any further questions feel free to ask me or any of our staff. You can recognize our staff from the badge they wear;Enjoy your stay in %hotelname% %username%!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_disable_effects', ':disableffects');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_disable_effects.keys', 'antieffects;disableffects');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_disable_effects.effects_enabled', 'Effects in this room have been enabled!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_disable_effects.effects_disabled', 'Effects in this room have been disabled!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_brb', ':brb');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_brb.keys', 'afk;brb;');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_brb.brb', '* %username% is now AFK! *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_brb.back', '* %username% is now back! *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_brb.time', '* %username% has now been away for %time% minutes *');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_nuke', ':nuke <username>');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_nuke.keys', 'nuke;nade;grenade;explode;boom');
INSERT INTO `emulator_texts` VALUES ('essentials.nuke.self', 'You can\'t nuke yourself, silly!');
INSERT INTO `emulator_texts` VALUES ('essentials.nuke.action', '* Launches nuke towards %username% *');
INSERT INTO `emulator_texts` VALUES ('essentials.nuke.nuked', '* %username% gets obliterated *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_buildheight.keys', 'buildheight;bh');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_buildheight.invalid_height', 'Invalid height! Build height must be between 0 - 40!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_buildheight.changed', 'Changed build height to %height%');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_buildheight.disabled', 'Build height removed.');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_buildheight.not_specified', 'No buildheight set. Height must be between 0 - 40.');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_slime', ':slime <username>');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_slime.keys', 'slime;slimed;goop;nickelodeon');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_slime.throws', '* Throws slime at %username%s direction *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_slime.missed', '* Missed %username%s face *');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_slime.slimed', '* Gets covered in slime by %username% *');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_explain', ':explain <command>');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_explain.keys', 'explain;commandinfo;commandhelp;aliases');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_explain.help', 'Specify a command to lookup. Example: :explain mimic');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_explain.notfound', 'Too bad but \'%command%\'-command does not seem to exist');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_explain.nopermission', 'You don\'t have permission to use %command%');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_explain.info', 'Information about the \'%command%\'-command:\rUsage: %description%\rKeys / Aliases:%keys%');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.keys', 'sellroom');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.removed', 'This room was remove from sale.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.invalid_credits', '%credits% credits is an invalid amount!');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.has_guild', 'Cannot sell this room, room has a guild.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.confirmed', 'This room is now up for sale for %credits% credits!');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.usage', 'Usage: :sellroom <credits>');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.forsale', 'This room is being sold by %ownername% for %credits%.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.notforsale', 'This room is not being sold.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.confirmkey', 'confirm');
INSERT INTO `emulator_texts` VALUES ('essentials.buyroom.has_guild', 'This room has a guild and therefor cannot be bought.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.owneroffline', 'Owner of this room, %username%, is offline.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.selfbuy', 'Silly %username%. You cannot buy your own room.');
INSERT INTO `emulator_texts` VALUES ('essentials.sellroom.buyroom.usage', 'To buy a room use :%key% %confirmkey%');
INSERT INTO `emulator_texts` VALUES ('essentials.buyroom.keys', 'buyroom');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_closedice', ':closedice [all]');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_closedice.keys', 'closedice;cd;sluitdices');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_closedice.keywordall', 'all');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_closedice.closed', '* Closes %count% dices *');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_set', ':set info');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_set.keys', 'set;changefurni');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_set.error', 'Use \':set info\' for more information!');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_set.invalid', 'Invalid item id %value%');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_set.notfound', 'Item not found.');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_set.wrong', 'Something went wrong.');
INSERT INTO `emulator_texts` VALUES ('essentials.cmd_set.succes', 'Updated!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_furnidata', ':furnidata');
INSERT INTO `emulator_texts` VALUES ('furnidata.cmd_furnidata.keys', 'furnidata');
INSERT INTO `emulator_texts` VALUES ('furnidata.cmd_furnidata.on', 'Successfully turned furnidata on!');
INSERT INTO `emulator_texts` VALUES ('furnidata.cmd_furnidata.off', 'Successfully turned furnidata off!');
INSERT INTO `emulator_texts` VALUES ('bubblealerts.notif_friendonline.message', '%username% just logged in! Say hi!');
INSERT INTO `emulator_texts` VALUES ('bubblealerts.notif_mention.message', '%username% mentioned you. Click to visit %username% in %room_name%!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_softkick', 'softkick');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_softkick_not_found', '%user% not found');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_softkick_error_self', 'You can not softkick yourself!');
INSERT INTO `emulator_texts` VALUES ('generic.error.ignore_higher_rank', 'You can\'t ignore this user.');
INSERT INTO `emulator_texts` VALUES ('error.bots.max.inventory', 'You can\'t buy or pickup anymore bots until you place some, the maximum amount of bots you are allowed is %amount%.');
INSERT INTO `emulator_texts` VALUES ('scripter.warning.item.bgtoner.permission', '%username% tried to change the background toner without rights in %room% owned by %owner%');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_subscription', 'subscription;sub');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.invalid_action', 'Invalid action specified. Must be add, +, remove or -');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.type_not_found', '%subscription% is not a valid subscription type');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.invalid_params_time', 'Invalid time span, try: x minutes/days/weeks/months');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.success_add_time', 'Successfully added %time% seconds to %subscription% on %user%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.user_not_have', '%user% does not have the %subscription% subscription');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.success_remove_time', 'Successfully removed %time% seconds from %subscription% on %user%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.success_remove_sub', 'Successfully removed %subscription% sub from %user%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.user_not_found', '%user% was not found');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_subscription.invalid_params', 'Invalid command format');
INSERT INTO `emulator_texts` VALUES ('subscriptions.hc.payday.message', 'Woohoo HC Payday has arrived! You have received %amount% credits to your purse. Enjoy!');
INSERT INTO `emulator_texts` VALUES ('hotel.room.tent.prefix', 'Tent');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_roombadge.no_badge', 'No badge specified!');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_roombadge', 'roombadge');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_roombadge', ':roombadge <badge>');
INSERT INTO `emulator_texts` VALUES ('wired.variable.name', '%name%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.roomname', '%roomname%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.user_count', '%user_count%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.owner', '%owner%');
INSERT INTO `emulator_texts` VALUES ('wired.variable.item_count', '%item_count%');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_stalk.forgot_username', 'Specify the username of the Habbo you want to follow!');
INSERT INTO `emulator_texts` VALUES ('commands.description.cmd_update_calendar', ':update_calendar');
INSERT INTO `emulator_texts` VALUES ('commands.keys.cmd_update_calendar', 'update_calendar');
INSERT INTO `emulator_texts` VALUES ('commands.success.cmd_update_calendar', 'Calendar updated successfully!');
INSERT INTO `emulator_texts` VALUES ('hotel.mannequin.name.default', 'My look');
INSERT INTO `emulator_texts` VALUES ('rcon.alert.user.change_username', 'You can change your username. Click on yourself to change it.');
INSERT INTO `emulator_texts` VALUES ('commands.error.cmd_changename.user_not_found', 'The Habbo %user% does not exist or is not online.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_changename.done', 'Successfully toggled the name change for the Habbo %user%.');
INSERT INTO `emulator_texts` VALUES ('commands.succes.cmd_changename.received', 'Hotel staff requests for you to change your name.\n Please click on your Habbo then click on the \"Change Your Name\" button.');

SET FOREIGN_KEY_CHECKS = 1;
