/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80030
 Source Host           : localhost:3306
 Source Schema         : ms3

 Target Server Type    : MySQL
 Target Server Version : 80030
 File Encoding         : 65001

 Date: 13/01/2023 17:20:14
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for emulator_settings
-- ----------------------------
DROP TABLE IF EXISTS `emulator_settings`;
CREATE TABLE `emulator_settings`  (
  `key` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `value` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`key`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of emulator_settings
-- ----------------------------
INSERT INTO `emulator_settings` VALUES ('hotel.home.room', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.welcome.alert.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.welcome.alert.message', 'Welcome to Habbo Hotel %user%!');
INSERT INTO `emulator_settings` VALUES ('hotel.max.duckets', '9000000');
INSERT INTO `emulator_settings` VALUES ('hotel.bots.max.room', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.bots.max.inventory', '25');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.owner', 'HabboHotel');
INSERT INTO `emulator_settings` VALUES ('hotel.shop.discount.modifier', '6');
INSERT INTO `emulator_settings` VALUES ('hotel.log.room.enter', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.log.chat', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.teleport.locked.allowed', '1');
INSERT INTO `emulator_settings` VALUES ('runtime.threads', '8');
INSERT INTO `emulator_settings` VALUES ('io.bossgroup.threads', '1');
INSERT INTO `emulator_settings` VALUES ('io.workergroup.threads', '5');
INSERT INTO `emulator_settings` VALUES ('hotel.log.chat.private', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.marketplace.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.ecotron.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.ecotron.rarity.chance.5', '2000');
INSERT INTO `emulator_settings` VALUES ('hotel.ecotron.rarity.chance.4', '200');
INSERT INTO `emulator_settings` VALUES ('hotel.ecotron.rarity.chance.3', '40');
INSERT INTO `emulator_settings` VALUES ('hotel.ecotron.rarity.chance.2', '4');
INSERT INTO `emulator_settings` VALUES ('hotel.ecotron.rarity.chance.1', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.pets.name.length.min', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.pets.name.length.max', '15');
INSERT INTO `emulator_settings` VALUES ('hotel.pets.max.room', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.pets.max.inventory', '25');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.points.freeze', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.points.block', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.points.effect', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.powerup.chance', '33');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.powerup.max.snowballs', '5');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.powerup.max.lives', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.onfreeze.loose.snowballs', '5');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.onfreeze.loose.explosionboost', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.onfreeze.time.frozen', '5');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.powerup.protection.time', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.gifts.special.price', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.freeze.powerup.protection.stack', '1');
INSERT INTO `emulator_settings` VALUES ('callback.post.errors', '1');
INSERT INTO `emulator_settings` VALUES ('callback.post.statistics', '1');
INSERT INTO `emulator_settings` VALUES ('callback.get.version', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.banzai.points.tile.steal', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.banzai.points.tile.fill', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.banzai.points.tile.lock', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.friendcategory', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.roomuser.idle.cycles', '300');
INSERT INTO `emulator_settings` VALUES ('hotel.wordfilter.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.wordfilter.rooms', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.wordfilter.messenger', '1');
INSERT INTO `emulator_settings` VALUES ('notify.staff.chat.auto.report', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.wordfilter.normalise', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.roomuser.idle.not_dancing.ignore.wired_idle', '0');
INSERT INTO `emulator_settings` VALUES ('pyramids.max.delay', '18');
INSERT INTO `emulator_settings` VALUES ('guardians.minimum.votes', '5');
INSERT INTO `emulator_settings` VALUES ('guardians.accept.timer', '90');
INSERT INTO `emulator_settings` VALUES ('guardians.maximum.resends', '2');
INSERT INTO `emulator_settings` VALUES ('guardians.maximum.guardians.total', '10');
INSERT INTO `emulator_settings` VALUES ('guardians.reporting.cooldown', '900');
INSERT INTO `emulator_settings` VALUES ('pirate_parrot.message.count', '6');
INSERT INTO `emulator_settings` VALUES ('pirate_parrot.message.bubble', '28');
INSERT INTO `emulator_settings` VALUES ('furniture.talking.range', '2');
INSERT INTO `emulator_settings` VALUES ('commands.cmd_chatcolor.banned_numbers', '23;33;34');
INSERT INTO `emulator_settings` VALUES ('seasonal.primary.type', '5');
INSERT INTO `emulator_settings` VALUES ('seasonal.types', '0;1;2;3;4;5;101;102;103;104;105');
INSERT INTO `emulator_settings` VALUES ('catalog.ltd.page.soldout', '761');
INSERT INTO `emulator_settings` VALUES ('bots.visitor.dateformat', 'yyyy-mm-dd HH:mm');
INSERT INTO `emulator_settings` VALUES ('wired.highscores.displaycount', '25');
INSERT INTO `emulator_settings` VALUES ('hotelview.promotional.points.type', '5');
INSERT INTO `emulator_settings` VALUES ('hotelview.promotional.reward.name', 'bonusbag20_2');
INSERT INTO `emulator_settings` VALUES ('hotelview.promotional.reward.id', '11043');
INSERT INTO `emulator_settings` VALUES ('hotelview.promotional.points', '100');
INSERT INTO `emulator_settings` VALUES ('commands.cmd_staffonline.min_rank', '2');
INSERT INTO `emulator_settings` VALUES ('bundle.bots.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('bundle.pets.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.trading.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('wired.effect.teleport.delay', '100');
INSERT INTO `emulator_settings` VALUES ('hotel.roomuser.idle.cycles.kick', '900');
INSERT INTO `emulator_settings` VALUES ('imager.location.badgeparts', '/var/www/testhotel/Cosmic/public/usercontent/badgeparts');
INSERT INTO `emulator_settings` VALUES ('imager.location.output.badges', '/var/www/testhotel/Cosmic/public/usercontent/badgeparts/generated/');
INSERT INTO `emulator_settings` VALUES ('imager.internal.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('db.min.partition.size', '1');
INSERT INTO `emulator_settings` VALUES ('db.max.partition.size', '2');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.pixels.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.pixels.amount', '100');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.pixels.interval', '600');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.pixels.ignore.idled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.pixels.ignore.hotelview', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.points.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.points.amount', '5');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.points.interval', '600');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.points.ignore.idled', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.points.ignore.hotelview', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.credits.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.credits.amount', '100');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.credits.interval', '600');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.credits.ignore.idled', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.credits.ignore.hotelview', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.max.bots.room', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.messenger.offline.messaging.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.catalog.discounts.amount', '6');
INSERT INTO `emulator_settings` VALUES ('hotel.rooms.auto.idle', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.room.enter.logs', '1');
INSERT INTO `emulator_settings` VALUES ('debug.mode', '1');
INSERT INTO `emulator_settings` VALUES ('debug.show.packets', '1');
INSERT INTO `emulator_settings` VALUES ('debug.show.packets.undefined', '1');
INSERT INTO `emulator_settings` VALUES ('debug.show.sql.exception', '1');
INSERT INTO `emulator_settings` VALUES ('logging.packets', '0');
INSERT INTO `emulator_settings` VALUES ('logging.packets.undefined', '0');
INSERT INTO `emulator_settings` VALUES ('logging.errors.packets', '0');
INSERT INTO `emulator_settings` VALUES ('logging.errors.sql', '1');
INSERT INTO `emulator_settings` VALUES ('logging.errors.runtime', '1');
INSERT INTO `emulator_settings` VALUES ('logging.debug', '0');
INSERT INTO `emulator_settings` VALUES ('save.room.chats', '1');
INSERT INTO `emulator_settings` VALUES ('save.private.chats', '1');
INSERT INTO `emulator_settings` VALUES ('marketplace.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.camera', '1');
INSERT INTO `emulator_settings` VALUES ('camera.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('camera.price.credits', '2');
INSERT INTO `emulator_settings` VALUES ('camera.price.points', '0');
INSERT INTO `emulator_settings` VALUES ('camera.price.points.publish', '10');
INSERT INTO `emulator_settings` VALUES ('camera.item_id', '45970');
INSERT INTO `emulator_settings` VALUES ('camera.extradata', '{\"t\":%timestamp%, \"u\":\"%id%\", \"s\":%room_id%, \"w\":\"%url%\"}');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.search.maxresults', '35');
INSERT INTO `emulator_settings` VALUES ('hotel.rooms.max.favorite', '30');
INSERT INTO `emulator_settings` VALUES ('catalog.guild.price', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.catalog.recycler.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('debug.show.errors', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.wired.furni.selection.count', '5');
INSERT INTO `emulator_settings` VALUES ('pathfinder.step.maximum.height', '1.1');
INSERT INTO `emulator_settings` VALUES ('pathfinder.step.allow.falling', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.rooms.handitem.time', '100');
INSERT INTO `emulator_settings` VALUES ('imager.url.youtube', 'imager.php?url=http://img.youtube.com/vi/%video%/default.jpg');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.popular.amount', '35');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.popular.listtype', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.inventory.max.items', '7500');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.chat.minimum.interval', '5');
INSERT INTO `emulator_settings` VALUES ('hotel.daily.respect', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.daily.respect.pets', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.refill.daily', '86400');
INSERT INTO `emulator_settings` VALUES ('monsterplant.seed.item_id', '4582');
INSERT INTO `emulator_settings` VALUES ('monsterplant.seed_rare.item_id', '4604');
INSERT INTO `emulator_settings` VALUES ('hotel.room.public.doortile.kick', '0');
INSERT INTO `emulator_settings` VALUES ('info.shown', '1');
INSERT INTO `emulator_settings` VALUES ('camera.publish.delay', '180');
INSERT INTO `emulator_settings` VALUES ('hotel.log.trades', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.butler.servedistance', '5');
INSERT INTO `emulator_settings` VALUES ('hotelview.halloffame.query', 'SELECT users.look, users.username, users.id, users_settings.hof_points FROM users_settings INNER JOIN users ON users_settings.user_id = users.id WHERE hof_points > 0 ORDER BY hof_points DESC, users.id ASC LIMIT 10');
INSERT INTO `emulator_settings` VALUES ('hotel.name', 'Habbo Hotel');
INSERT INTO `emulator_settings` VALUES ('hotel.player.name', 'Habbo');
INSERT INTO `emulator_settings` VALUES ('catalog.page.vipgifts', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.rollers.speed.maximum', '100');
INSERT INTO `emulator_settings` VALUES ('seasonal.currency.ducket', '0');
INSERT INTO `emulator_settings` VALUES ('seasonal.currency.pixel', '0');
INSERT INTO `emulator_settings` VALUES ('seasonal.currency.diamond', '5');
INSERT INTO `emulator_settings` VALUES ('seasonal.currency.shell', '4');
INSERT INTO `emulator_settings` VALUES ('seasonal.currency.names', 'ducket;pixel;shell;diamond');
INSERT INTO `emulator_settings` VALUES ('hotel.room.tags.staff', 'staff;official;habbo');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.popular.category.maxresults', '10');
INSERT INTO `emulator_settings` VALUES ('debug.show.users', '1');
INSERT INTO `emulator_settings` VALUES ('room.chat.delay', '0');
INSERT INTO `emulator_settings` VALUES ('room.chat.prefix.format', '[<font color=\"%color%\">%prefix%</font>] ');
INSERT INTO `emulator_settings` VALUES ('camera.use.https', '1');
INSERT INTO `emulator_settings` VALUES ('basejump.url', 'http://localhost/game/BaseJump.swf');
INSERT INTO `emulator_settings` VALUES ('basejump.assets.url', 'http://localhost/gamecenter/gamecenter_basejump/BasicAssets.swf');
INSERT INTO `emulator_settings` VALUES ('hotel.marketplace.currency', '0');
INSERT INTO `emulator_settings` VALUES ('networking.tcp.proxy', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.calendar.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('images.gamecenter.snowwar', 'c_images/gamecenter_snowwar/');
INSERT INTO `emulator_settings` VALUES ('images.gamecenter.basejump', 'c_images/gamecenter_basejump/');
INSERT INTO `emulator_settings` VALUES ('hotel.purchase.ltd.limit.daily.total', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.purchase.ltd.limit.daily.item', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.catalog.ltd.limit.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.welcome.alert.oldstyle', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.welcome.alert.delay', '10000');
INSERT INTO `emulator_settings` VALUES ('hotel.calendar.starttimestamp', '1593561600');
INSERT INTO `emulator_settings` VALUES ('hotel.room.nooblobby', '3');
INSERT INTO `emulator_settings` VALUES ('hotel.floorplan.max.widthlength', '64');
INSERT INTO `emulator_settings` VALUES ('hotel.floorplan.max.totalarea', '4096');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.max.chatlength', '120');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.max.namelength', '15');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.max.chatdelay', '604800');
INSERT INTO `emulator_settings` VALUES ('hotel.chat.max.length', '100');
INSERT INTO `emulator_settings` VALUES ('hotel.view.ltdcountdown.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.view.ltdcountdown.timestamp', '1519496132');
INSERT INTO `emulator_settings` VALUES ('hotel.view.ltdcountdown.itemid', '10388');
INSERT INTO `emulator_settings` VALUES ('hotel.view.ltdcountdown.pageid', '13');
INSERT INTO `emulator_settings` VALUES ('hotel.view.ltdcountdown.itemname', 'trophy_netsafety_0');
INSERT INTO `emulator_settings` VALUES ('io.client.multithreaded.handler', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.room.stickypole.prefix', '%timestamp%, %username%:\\r');
INSERT INTO `emulator_settings` VALUES ('hotel.trading.requires.perk', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.targetoffer.id', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.wordfilter.replacement', 'bobba');
INSERT INTO `emulator_settings` VALUES ('debug.show.headers', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.catalog.purchase.cooldown', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.catalog.items.display.ordernum', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.talenttrack.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.sort.ordernum', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.wordfilter.automute', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.furni.gym.achievement.olympics_c16_trampoline', 'Trampolinist');
INSERT INTO `emulator_settings` VALUES ('hotel.furni.gym.achievement.olympics_c16_crosstrainer', 'CrossTrainer');
INSERT INTO `emulator_settings` VALUES ('hotel.furni.gym.achievement.olympics_c16_treadmill', 'Jogger');
INSERT INTO `emulator_settings` VALUES ('hotel.furni.gym.forcerot.olympics_c16_trampoline', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.furni.gym.forcerot.olympics_c16_crosstrainer', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.furni.gym.forcerot.olympics_c16_treadmill', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.messenger.search.maxresults', '50');
INSERT INTO `emulator_settings` VALUES ('hotel.alert.oldstyle', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.staffpicks.categoryid', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.room.rollers.norules', '0');
INSERT INTO `emulator_settings` VALUES ('postit.charlimit', '366');
INSERT INTO `emulator_settings` VALUES ('hotel.rooms.deco_hosting', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.navigator.populartab.publics', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.butler.commanddistance', '5');
INSERT INTO `emulator_settings` VALUES ('catalog.guild.hc_required', '1');
INSERT INTO `emulator_settings` VALUES ('catalog.ltd.random', '1');
INSERT INTO `emulator_settings` VALUES ('commands.plugins.oldstyle', '0');
INSERT INTO `emulator_settings` VALUES ('scripter.modtool.tickets', '1');
INSERT INTO `emulator_settings` VALUES ('invisible.prevent.chat', '0');
INSERT INTO `emulator_settings` VALUES ('discount.max.allowed.items', '100');
INSERT INTO `emulator_settings` VALUES ('discount.batch.size', '6');
INSERT INTO `emulator_settings` VALUES ('discount.batch.free.items', '1');
INSERT INTO `emulator_settings` VALUES ('discount.bonus.min.discounts', '1');
INSERT INTO `emulator_settings` VALUES ('discount.additional.thresholds', '40;99');
INSERT INTO `emulator_settings` VALUES ('team.wired.update.rc-1', 'DO NOT REMOVE THIS SETTING!');
INSERT INTO `emulator_settings` VALUES ('hotel.room.floorplan.check.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.interval', '600');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.ignore.idled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.ignore.hotelview', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.type', '4');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.name', 'shell');
INSERT INTO `emulator_settings` VALUES ('camera.url', 'http://localhost/usercontent/camera/');
INSERT INTO `emulator_settings` VALUES ('imager.location.output.camera', '/var/www/testhotel/Cosmic/public/usercontent/camera/');
INSERT INTO `emulator_settings` VALUES ('imager.location.output.thumbnail', '/var/www/testhotel/Cosmic/public/usercontent/camera/thumbnail/');
INSERT INTO `emulator_settings` VALUES ('path.furniture.icons', '${image.library.url}/icons/');
INSERT INTO `emulator_settings` VALUES ('bubblealerts.notif_purchase.limited', '0');
INSERT INTO `emulator_settings` VALUES ('bubblealerts.notif_marketplace.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.room.furni.max', '2500');
INSERT INTO `emulator_settings` VALUES ('hotel.sanctions.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('navigator.eventcategories', '1,Hottest Events,false;2,Parties & Music,true;3,Role Play,true;4,Help Desk,true;5,Trading,true;6,Games,true;7,Debates & Discussions,true;8,Grand Openings,true;9,Friending,true;10,Jobs,true;11,Group Events,true');
INSERT INTO `emulator_settings` VALUES ('room.promotion.badge', 'RADZZ');
INSERT INTO `emulator_settings` VALUES ('camera.price.points.publish.type', '0');
INSERT INTO `emulator_settings` VALUES ('camera.price.points.type', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.bot.placement.messages', 'Yo!;Hello I\'m a real party animal!;Hello!');
INSERT INTO `emulator_settings` VALUES ('rosie.bubble.image.url', '${image.library.url}notifications/generic.png');
INSERT INTO `emulator_settings` VALUES ('rosie.buyroom.currency.type', '5');
INSERT INTO `emulator_settings` VALUES ('allowed.username.characters', 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=!?@:,.');
INSERT INTO `emulator_settings` VALUES ('essentials.cmd_kill.effect.victim', '93;89');
INSERT INTO `emulator_settings` VALUES ('essentials.cmd_kill.effect.killer', '164;182');
INSERT INTO `emulator_settings` VALUES ('bubblealerts.notif_friendonline.image', '${image.library.url}notifications/figure?p=%figure%');
INSERT INTO `emulator_settings` VALUES ('bubblealerts.notif_friendonline.useimage', '1');
INSERT INTO `emulator_settings` VALUES ('bubblealerts.notif_friendonline.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.enabled', 'true');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.game.background.color', '93d4f3');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.game.text.color', '000000');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.game.start.time', '15');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.players.min', '2');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.room.id', '0');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.assets', 'http://localhost/swf/c_images/gamecenter_snowwar/');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.artic.bg', 'http://localhost/swf/c_images/gamecenter_snowwar/snst_bg_1_a_big.png');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.dragoncave.bg', 'http://localhost/swf/c_images/gamecenter_snowwar/snst_bg_2_big.png');
INSERT INTO `emulator_settings` VALUES ('gamecenter.snowwar.fightnight.bg', 'http://localhost/swf/c_images/gamecenter_snowwar/snst_bg_3_noscale.png');
INSERT INTO `emulator_settings` VALUES ('gamecenter.fastfood.enabled', 'true');
INSERT INTO `emulator_settings` VALUES ('gamecenter.fastfood.background.color', '68bbd2');
INSERT INTO `emulator_settings` VALUES ('gamecenter.fastfood.text.color', 'ffffff');
INSERT INTO `emulator_settings` VALUES ('gamecenter.fastfood.assets', 'http://localhost/swf/c_images/gamecenter_basejump/');
INSERT INTO `emulator_settings` VALUES ('gamecenter.fastfood.apiKey', '');
INSERT INTO `emulator_settings` VALUES ('gamecenter.fastfood.theme', 'default');
INSERT INTO `emulator_settings` VALUES ('hotel.room.stickies.max', '200');
INSERT INTO `emulator_settings` VALUES ('retro.style.homeroom', '1');
INSERT INTO `emulator_settings` VALUES ('enc.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('enc.e', '');
INSERT INTO `emulator_settings` VALUES ('enc.n', '');
INSERT INTO `emulator_settings` VALUES ('enc.d', '');
INSERT INTO `emulator_settings` VALUES ('db.pool.maxsize', '12');
INSERT INTO `emulator_settings` VALUES ('db.pool.minsize', '8');
INSERT INTO `emulator_settings` VALUES ('hotel.item.trap.pirate_sandtrap', '3000');
INSERT INTO `emulator_settings` VALUES ('hotel.item.trap.hween14_rare2', '3000');
INSERT INTO `emulator_settings` VALUES ('hotel.item.trap.hween_c17_handstrap', '3000');
INSERT INTO `emulator_settings` VALUES ('hotel.item.trap.hween_c17_spiketrap', '3000');
INSERT INTO `emulator_settings` VALUES ('flood.with.rights', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.allow.ignore.staffs', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.gifts.box_types', '0,1,2,3,4,5,6,8');
INSERT INTO `emulator_settings` VALUES ('hotel.gifts.ribbon_types', '0,1,2,3,4,5,6,7,8,9,10');
INSERT INTO `emulator_settings` VALUES ('hotel.flood.mute.time', '30');
INSERT INTO `emulator_settings` VALUES ('hotel.jukebox.limit.large', '20');
INSERT INTO `emulator_settings` VALUES ('hotel.jukebox.limit.normal', '10');
INSERT INTO `emulator_settings` VALUES ('apollyon.cooldown.amount', '250');
INSERT INTO `emulator_settings` VALUES ('ftp.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('ftp.user', 'root');
INSERT INTO `emulator_settings` VALUES ('ftp.password', 'password123');
INSERT INTO `emulator_settings` VALUES ('ftp.host', 'example.com');
INSERT INTO `emulator_settings` VALUES ('hotel.room.rollers.roll_avatars.max', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.nux.gifts.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.next_date', '2023-01-15 00:00:00');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.interval', '1 month');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.query', 'SELECT SUM(cost_credits) AS `amount_spent` FROM `logs_shop_purchases` WHERE `user_id` = @user_id AND `timestamp` > @timestamp_start AND `timestamp` <= @timestamp_end AND `catalog_name` NOT LIKE \'CF_%\' AND `catalog_name` NOT LIKE \'CFC_%\';');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.streak', '7=5;30=10;60=15;90=20;180=25;365=30');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.currency', 'credits');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.percentage', '10');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.payday.creditsspent_reset_on_expire', '1');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.achievement', 'VipHC');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.discount.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('subscriptions.hc.discount.days_before_end', '7');
INSERT INTO `emulator_settings` VALUES ('subscriptions.scheduler.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('subscriptions.scheduler.interval', '10');
INSERT INTO `emulator_settings` VALUES ('hotel.users.clothingvalidation.onhcexpired', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.users.clothingvalidation.onlogin', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.users.clothingvalidation.onchangelooks', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.users.clothingvalidation.onmimic', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.users.clothingvalidation.onmannequin', '0');
INSERT INTO `emulator_settings` VALUES ('hotel.users.clothingvalidation.onfballgate', '0');
INSERT INTO `emulator_settings` VALUES ('gamedata.figuredata.url', 'https://habbo.com/gamedata/figuredata/0');
INSERT INTO `emulator_settings` VALUES ('hotel.users.max.friends', '300');
INSERT INTO `emulator_settings` VALUES ('hotel.users.max.friends.hc', '1100');
INSERT INTO `emulator_settings` VALUES ('hotel.users.max.rooms', '50');
INSERT INTO `emulator_settings` VALUES ('hotel.users.max.rooms.hc', '75');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.pixels.hc_modifier', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.points.hc_modifier', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.credits.hc_modifier', '1');
INSERT INTO `emulator_settings` VALUES ('hotel.auto.gotwpoints.hc_modifier', '1');
INSERT INTO `emulator_settings` VALUES ('room.chat.mutearea.allow_whisper', '1');
INSERT INTO `emulator_settings` VALUES ('easter_eggs.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('bubblealerts.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('wired.place.under', '0');
INSERT INTO `emulator_settings` VALUES ('wired.custom.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('console.mode', '1');
INSERT INTO `emulator_settings` VALUES ('youtube.apikey', '');
INSERT INTO `emulator_settings` VALUES ('hotel.gifts.length.max', '300');
INSERT INTO `emulator_settings` VALUES ('hotel.trophies.length.max', '300');
INSERT INTO `emulator_settings` VALUES ('hotel.calendar.default', 'test');
INSERT INTO `emulator_settings` VALUES ('hotel.calendar.pixels.hc_modifier', '2.0');
INSERT INTO `emulator_settings` VALUES ('moodlight.color_check.enabled', '1');
INSERT INTO `emulator_settings` VALUES ('custom.stacking.enabled', '0');
INSERT INTO `emulator_settings` VALUES ('redeem.currency.trade', '1');

SET FOREIGN_KEY_CHECKS = 1;
